### ISSUE TITLE
CLEVR数据集评估

### ISSUE THREAD

**Issue by Rushing-Life** [shenxiang-vqa/LSAT#3]
您好，非常感谢您的工作，我有一个问题想咨询您。请问如何在线评估CLEVR数据集的test.txt呢？是在这个网站上吗？[](https://eval.ai/web/challenges/list)我没有找到，您方便解答我的疑惑吗。 希望收到您的回复，谢谢。

**Comment by shenxiang-vqa** [comment]
clevr我没有在线评估的，在线评估需要申请。我是用train的训练模式，边训练边验证

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月01日 22:02 |
| 收件人 | shenxiang-vqa/LSAT ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [shenxiang-vqa/LSAT] CLEVR数据集评估 (Issue #3) |

Closed #3 as completed.
